### ISSUE TITLE
Receiving `Internal Server Error` for some API endpoints

### ISSUE THREAD

**Issue by KartikWatts** [chesslablab/chess-api#175]
I might be missing something, would be grateful if could be assisted. After spending a lot of time, as much as I could try, it seems to me, that some of the APIs are ending up in Internal Server Error, like:
1. `POST` on `/v1/autocomplete/player`
2. `GET` on `/v1/stats/opening`
3. `POST` on `/v1/stats/player`
4. `POST` on `/v1/stats/event`
and some other APIs are failing, while others are working perfectly fine for me.
I have all the 4 containers working in Docker: `chess_api_php_fpm`, ` chess-data-php_fpm`, `chess_server_php_fpm`, `chess_website_php_fpm`, including other service containers like mysql and nginx.

Couldn't find anything relevant from docker logs for chess_api_php_fpm:
```
❯ docker logs -n 20 -f chess_api_php_fpm
172.23.0.2 -  16/Jul/2024:12:39:24 +0000 "GET /index.php" 200
NOTICE: PHP message: [info] Matched route "v1_play_rav".
NOTICE: PHP message: [info] Deprecated: str_ends_with(): Passing null to parameter #1 ($haystack) of type string is deprecated
NOTICE: PHP message: [info] Deprecated: str_ends_with(): Passing null to parameter #1 ($haystack) of type string is deprecated
NOTICE: PHP message: [info] Deprecated: str_ends_with(): Passing null to parameter #1 ($haystack) of type string is deprecated
172.23.0.2 -  16/Jul/2024:12:39:29 +0000 "POST /index.php" 200
NOTICE: PHP message: [info] Matched route "v1_eval_names".
172.23.0.2 -  16/Jul/2024:12:40:22 +0000 "POST /index.php" 200
NOTICE: PHP message: [info] Matched route "v1_eval_names".
172.23.0.2 -  16/Jul/2024:12:41:38 +0000 "POST /index.php" 200
NOTICE: PHP message: [info] Matched route "v1_stats_opening".
172.23.0.2 -  16/Jul/2024:12:41:39 +0000 "GET /index.php" 500
NOTICE: PHP message: [info] Matched route "v1_eval_names".
172.23.0.2 -  16/Jul/2024:12:42:16 +0000 "POST /index.php" 200
NOTICE: PHP message: [info] Matched route "v1_stats_player".
172.23.0.2 -  16/Jul/2024:12:42:19 +0000 "POST /index.php" 500
NOTICE: PHP message: [info] Matched route "v1_eval_names".
172.23.0.2 -  16/Jul/2024:12:43:01 +0000 "POST /index.php" 200
NOTICE: PHP message: [info] Matched route "v1_stats_event".
172.23.0.2 -  16/Jul/2024:12:43:03 +0000 "POST /index.php" 500
```

I tried to create test method of my own in `AutocompleteEventController`, but that was also ending up in Internal server error, while the same method was working for me in `AnnotationsGamesController` for instance, when linked through routes.yaml; I thought it could be some dependency issue, reinstalled the composer packages, but same case.

Any idea, if you can kindly help me figure this out @programarivm , would be really helpful. Regards.

**Comment by KartikWatts** [comment]
@programarivm Yes, I tried again today. Reinstalling all the containers, and installing composer packages; not working.
Planning to try again tomorrow cloning all the repos again, couldn't understand, why some of the APIs are resulting in the Internal Server Error, while others are working fine. Will inform you.

**Comment by programarivm** [comment]
@KartikWatts since the endpoints listed above are querying the database there must be something to do with the database connection. Did you set the `DB_HOST` variable in your `.env` file to the IP address of the chess database?

**Comment by KartikWatts** [comment]
@programarivm Thanks a lot, it's resolved and working for me now 😃🙏, thanks to my limited knowledge regarding communication among different docker containers 🤦, I updated the `DB_HOST` for `chess_api` container as per the `chess_data` container ip, working fine now, we can close this issue. Regards.
