### ISSUE TITLE
Implement the GET /api/annotations/games endpoint

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-api#51]
This endpoint is intended to fetch all annotated games in [data/annotations/games.json](https://github.com/chesslablab/chess-api/blob/main/data/annotations/games.json). 

It returns JSON data from a file in a similar way as with:

- GET /autocomplete
- GET /stats/opening

Thus, a new controller called ChessApi\Controller\AnnotationsGames needs to be created, and its code should be quite similar to the following:

- [ChessApi\Controller\AutocompleteController](https://github.com/chesslablab/chess-api/blob/main/src/Controller/AutocompleteController.php)
- [ChessApi\Controller\StatsOpeningController](https://github.com/chesslablab/chess-api/blob/main/src/Controller/StatsOpeningController.php)

See:

- [Chess API for Web Apps](https://chess-api.readthedocs.io/en/latest/)

Keep it up, and happy coding!

**Comment by SmashedFrenzy16** [comment]
Hi there, happy learning and coding!

**Comment by SmashedFrenzy16** [comment]
@programarivm, I have fixed the issue. Here is the PR: https://github.com/chesslablab/chess-api/pull/52
