### ISSUE TITLE
Add annotated chess games

### ISSUE THREAD

**Issue by programarivm** [chesslablab/chess-api#73]
Annotated games are games with comments that help understand what is going on the chessboard. They usually include variations showing the development of the game in selected positions that require an in-depth understanding. RAV stands for Recursive Annotation Variation. This is the standard format for annotated chess games.

![Screenshot 2023-08-16 12:34:36](https://github.com/chesslablab/chess-api/assets/4062000/7f6581f2-4ecf-4dd6-94e8-e26f3481845e)
**Figure 1**. Click on **Database > Annotated Games** and select a chess game.

![q_09_figure_02](https://github.com/chesslablab/react-chess/assets/4062000/47455065-ff2b-49b3-8e50-8b52abfee89b)
**Figure 2**. Read the comments and explore the variations.

At this moment, the annotated games are being added to the [data/annotations/games.json](https://github.com/chesslablab/chess-api/blob/main/data/annotations/games.json) file. While the chess games database contains one million records, there are only a few annotated chess games. This is mainly because annotations may be subject to copyright.

Described next are the games to be added.

## World Chess Championship 1921

World Chess Championship 1921. (2023, August 9). In Wikipedia. [https://en.wikipedia.org/wiki/World_Chess_Championship_1921](https://en.wikipedia.org/wiki/World_Chess_Championship_1921)

- [x] https://github.com/chesslablab/chess-api/issues/69 
- [x] https://github.com/chesslablab/chess-api/issues/70
- [x] https://github.com/chesslablab/chess-api/issues/71
- [x] https://github.com/chesslablab/chess-api/issues/72

---

## © Copyrighted Annotations

Copyright permissions have been obtained from the authors to get annotated chess games published into [chesslablab.com](https://www.chesslablab.com/). Should you publish these games into your fork of ChesslaBlab, please also ask the authors for copyright permissions.

- [x] https://github.com/chesslablab/chess-api/issues/95 
- [x] https://github.com/chesslablab/chess-api/issues/96
- [x] https://github.com/chesslablab/chess-api/issues/98
- [x] https://github.com/chesslablab/chess-api/issues/99
- [x] https://github.com/chesslablab/chess-api/issues/100
- [x] https://github.com/chesslablab/chess-api/issues/116

### World Chess Championship 2004

- [x] https://github.com/chesslablab/chess-api/issues/102
- [x] https://github.com/chesslablab/chess-api/issues/103
- [x] https://github.com/chesslablab/chess-api/issues/104
- [x] https://github.com/chesslablab/chess-api/issues/105
- [x] https://github.com/chesslablab/chess-api/issues/106
- [x] https://github.com/chesslablab/chess-api/issues/107
- [x] https://github.com/chesslablab/chess-api/issues/108
- [x] https://github.com/chesslablab/chess-api/issues/109
- [x] https://github.com/chesslablab/chess-api/issues/110
- [x] https://github.com/chesslablab/chess-api/issues/111
- [x] https://github.com/chesslablab/chess-api/issues/112
- [x] https://github.com/chesslablab/chess-api/issues/113
- [x] https://github.com/chesslablab/chess-api/issues/114
- [x] https://github.com/chesslablab/chess-api/issues/115

**Comment by CodeMaster7000** [comment]
@programarivm Has this issue been completed now?

**Comment by programarivm** [comment]
Not yet, still searching for annotated games in the public domain.

**Comment by programarivm** [comment]
👋 Hello @chesslablab/annotated-games team,

A bunch of amazing, annotated chess games are being added to the [data/annotations/games.json](https://github.com/chesslablab/chess-api/blob/main/data/annotations/games.json) file according to a coding convention.

As you can see, all games contain these PGN tags.

- `Event`
- `Round`
- `Site`
- `Date`
- `White`
- `Black`
- `WhiteElo`
- `BlackElo`
- `Result`
- `ECO`
- `movetext`

So far so good, all tags except `movetext` are self-explanatory, however, the `movetext` tag does follow a coding convention because it is written in RAV format.

See: 

- [8.2.5: Movetext RAV (Recursive Annotation Variation)](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.2.5)

In other words, the `movetext` tag needs to be filtered for further processing.

- An introduction enclosed in curly brackets is always found at the beginning of the movetext, e.g. `{ Adapted notes, originally by J. R. Capablanca. }`
- No blank space is left between a move number and a chess move, e.g. `21.Qc6`, `21...Rd8`
- A blank space is left between two chess moves, e.g. `23.Ne4 Nb8`
- A blank space is left between a chess move and a variation, e.g. `21.Qc6 (21.Qxe7)`
- A move number is always found right after a closing parenthesis, e.g. `21.Qc6 (21.Qxe7) 21...Rd8`
- [Numeric Annotation Glyphs](https://en.wikipedia.org/wiki/Numeric_Annotation_Glyphs) (NAGs) are used for specific meanings, e.g. `$1`, `$40`   

[tests/unit/Play/RavPlayTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Play/RavPlayTest.php) contains examples showing how a RAV movetext can be filtered using the `filtered()` method. 

- [filtered_e4_e5__h5()](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Play/RavPlayTest.php#L244)
- [validate_e4_c5__e6()](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Play/RavPlayTest.php#L1150)

The RAV reader at chesslablab.com displays the variation levels in different shades of gray. It is a 2D scrollable HTML table where the main line is shown in a white background color. The deeper the level, the darker the background color is displayed.

![figure_01](https://github.com/chesslablab/chess-api/assets/4062000/7878ebab-525c-453f-8410-848831526b7f)
**Figure 1**. Click on **Database > Annotated Games** and select a game.

Having said all that, the present issue contains a bunch of filtered games already which are to be added to the [data/annotations/games.json](https://github.com/chesslablab/chess-api/blob/main/data/annotations/games.json) file. The thing is, the variations in these games are not encoded properly in RAV format so the games are shown in a white background color as in the example below.

![figure_02](https://github.com/chesslablab/chess-api/assets/4062000/7561e5f0-ecb0-4287-810a-1d4a3e1d3321)
**Figure 2**. Click on **Analysis Board > Rav Movetext** and load a RAV movetext.

Thus, the task to be done is make sure the games follow the coding convention described in the present issue. The variations need to be encoded properly so the ChesslaBlab RAV reader can display the depth levels in different shades of gray.

Keep it up, and stay tuned for the games!

**Comment by programarivm** [comment]
👋 Hey @chesslablab/annotated-games team,

Thank you for sending pull requests! It looks like this issue needs some more information, so let me show you an example. 

This is a PHP script called `cli/annotations.php` that filters a movetext for further processing.

```php
<?php

use Chess\Play\RavPlay;

require __DIR__  . '/../vendor/autoload.php';

$movetext = "1. Nf3 { Notes by Raymond Keene. } d5 2. b3 Bg4 3. Bb2 Nd7
    4. g3 Bxf3 {A bold decision indicating that Black is playing
    for a win. This was the last round and if Kovacevic could beat
    me he would have tied with me.} 5. exf3 Ngf6 6. f4 e6 7. Bg2
    {?! Dubious. 7 Bh3! intending the disruptive advance f4-f5 is
    less stereotyped.} 7...Be7 8. O-O O-O 9. d3 a5 10. a4 c6
    11. Nd2 b5 12. Qe2 bxa4 {? Now White obtains the upper
    hand. It was essential for Black to maintain the tension with
    moves such as ...Rb8 and ...Re8 when his position would even
    be slightly preferable.} 13. Rxa4 Nb6 14. Ra2 {!} a4 15. Rfa1
    axb3 16. Rxa8 Nxa8 17. Nxb3 Nb6 {Not good: White now has the
    opportunity to launch a variety of favourable combinations,
    but it's clear that Black's position is already far from
    satisfactory (White is better developed and his well
    cO-Ordinated pieces control the vital a-file and a1-h8
    diagonal).} 18. f5 {! Inaugurating the combination. Black must
    accept the sacrifice, otherwise (after 19 fxe6) he would shed
    his e-pawn to the combined onslaught of White's pieces.}
    18...exf5 19. Nd4 Qd7 20. Bh3 {! Also good was 20 Nxc6 Qxc6 21
    Qxe7 but the text is more accurate. Black cannot allow the
    white knight to reach f5 since the threats against g7 would be
    intolerable.} 20...g6 {Or 20...Ng4 21 Nxf5!} 21. Bxf5 {!! Once
    again 21 Nxc6 Qxc6 22 Qxe7 was very good, but White has
    something more ambitious in mind.} 21...gxf5 22. Ra7 {!! This
    move visibly came as a shock to my opponent. Black has no
    choice but to fall in with White's plans.} 22...Qxa7 23. Nxc6
    Qd7 {There are two major alternative defences: a) 23...Qa2 24
    Nxe7+ Kg7 25 Nxf5+ Kg8 (or 25...Kg6 26 Ne7+ Kg7 27 Qg4+) 26
    Qg4+ Nxg4 27 Ne7 mate. b) 23...Ba3! (Best) 24 Nxa7 (24 Bxf6
    Qa4! is highly unclear) 24...Bxb2 when White has queen for
    rook and two pieces, but Black's forces are rather awkwardly
    placed and this enables White to increase his advantage as
    follows: 25 c4! Bd4 26 Nb5 Re8! 27 Qf3 Bc5 28 d4 Bf8 29 c5 Nc4
    30 Qxf5, and in view of the powerful c-pawn, Black's weakened
    kingside and the scattered dispositions of the black army,
    White should win. However, this was Black's only chance of
    resistance. But, as so often, a combinational blow disturbs
    the balance of the victim's objectivity and he fails to
    discover the most tenacious defensive possibilities.}
    24. Nxe7+ Kg7 25. Qh5 {! Completely unanswerable. For example:
    25...Qxe7 26 Qg5+ Kh8 27 Bxf6+ picking up the other knight in
    addition; or 25...h6 26 Nxf5+ or 25...Ra8 26 Qg5+ Kf8 27 Bxf6
    with Qg8 mate to follow.} 1-0";

$ravPlay = (new RavPlay($movetext))->validate();

$filtered = $ravPlay->getRavMovetext()->filtered();

echo $filtered . PHP_EOL;
```

```text
php cli/annotations.php 
1.Nf3 {Notes by Raymond Keene.} d5 2.b3 Bg4 3.Bb2 Nd7 4.g3 Bxf3 {A bold decision indicating that Black is playing for a win. This was the last round and if Kovacevic could beat me he would have tied with me.} 5.exf3 Ngf6 6.f4 e6 7.Bg2 {?! Dubious. 7 Bh3! intending the disruptive advance f4-f5 is less stereotyped.} 7...Be7 8.O-O O-O 9.d3 a5 10.a4 c6 11.Nd2 b5 12.Qe2 bxa4 {? Now White obtains the upper hand. It was essential for Black to maintain the tension with moves such as...Rb8 and...Re8 when his position would even be slightly preferable.} 13.Rxa4 Nb6 14.Ra2 {!} a4 15.Rfa1 axb3 16.Rxa8 Nxa8 17.Nxb3 Nb6 {Not good: White now has the opportunity to launch a variety of favourable combinations, but it's clear that Black's position is already far from satisfactory (White is better developed and his well cO-Ordinated pieces control the vital a-file and a1-h8 diagonal).} 18.f5 {! Inaugurating the combination. Black must accept the sacrifice, otherwise (after 19 fxe6) he would shed his e-pawn to the combined onslaught of White's pieces.} 18...exf5 19.Nd4 Qd7 20.Bh3 {! Also good was 20 Nxc6 Qxc6 21 Qxe7 but the text is more accurate. Black cannot allow the white knight to reach f5 since the threats against g7 would be intolerable.} 20...g6 {Or 20...Ng4 21 Nxf5!} 21.Bxf5 {!! Once again 21 Nxc6 Qxc6 22 Qxe7 was very good, but White has something more ambitious in mind.} 21...gxf5 22.Ra7 {!! This move visibly came as a shock to my opponent. Black has no choice but to fall in with White's plans.} 22...Qxa7 23.Nxc6 Qd7 {There are two major alternative defences: a) 23...Qa2 24 Nxe7+ Kg7 25 Nxf5+ Kg8 (or 25...Kg6 26 Ne7+ Kg7 27 Qg4+) 26 Qg4+ Nxg4 27 Ne7 mate. b) 23...Ba3! (Best) 24 Nxa7 (24 Bxf6 Qa4! is highly unclear) 24...Bxb2 when White has queen for rook and two pieces, but Black's forces are rather awkwardly placed and this enables White to increase his advantage as follows: 25 c4! Bd4 26 Nb5 Re8! 27 Qf3 Bc5 28 d4 Bf8 29 c5 Nc4 30 Qxf5, and in view of the powerful c-pawn, Black's weakened kingside and the scattered dispositions of the black army, White should win. However, this was Black's only chance of resistance. But, as so often, a combinational blow disturbs the balance of the victim's objectivity and he fails to discover the most tenacious defensive possibilities.} 24.Nxe7+ Kg7 25.Qh5 {! Completely unanswerable. For example: 25...Qxe7 26 Qg5+ Kh8 27 Bxf6+ picking up the other knight in addition; or 25...h6 26 Nxf5+ or 25...Ra8 26 Qg5+ Kf8 27 Bxf6 with Qg8 mate to follow.}
```

It is the filtered movetext what needs to be added to [data/annotations/games.json](https://github.com/chesslablab/chess-api/blob/main/data/annotations/games.json).

However, the variations in a filtered movetext may not be encoded properly in RAV format so the game is shown as if being a main line in a white background color. The variations need to be encoded properly so the ChesslaBlab RAV reader can display the depth levels in different shades of gray.

Happy coding!

**Comment by SmashedFrenzy16** [comment]
@programarivm, when testing the PHP file, I got and error here: 

```
Stack trace:
#0 {main}
```
This error was thrown by line 5 of the code above, whcih was `require __DIR__  . '/../vendor/autoload.php';`

How do you solve this?

**Comment by programarivm** [comment]
@SmashedFrenzy16 make sure to run `composer install` before running the script.

Keep it up,

**Comment by SmashedFrenzy16** [comment]
Thanks @programarivm!

**Comment by SmashedFrenzy16** [comment]
@programarivm I also got the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Chess\Play\msgpack_unpack() in C:\Users\22RTaha\Downloads\vendor\chesslablab\php-chess\src\Play\RavPlay.php:43
Stack trace:
#0 C:\Users\22RTaha\Downloads\test.php(51): Chess\Play\RavPlay->__construct()
#1 {main}
  thrown in C:\Users\22RTaha\Downloads\vendor\chesslablab\php-chess\src\Play\RavPlay.php on line 43
```

How do I also solve this?

**Comment by SmashedFrenzy16** [comment]
@programarivm I also got the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Chess\Play\msgpack_unpack() in C:\Users\<USERNAME>\Downloads\vendor\chesslablab\php-chess\src\Play\RavPlay.php:43
Stack trace:
#0 C:\Users\<USERNAME>\Downloads\test.php(51): Chess\Play\RavPlay->__construct()
#1 {main}
  thrown in C:\Users\<USERNAME>\Downloads\vendor\chesslablab\php-chess\src\Play\RavPlay.php on line 43
```
How do I also solve this?

PS: Also ignore the <USERNAME> part in the path file, I just replaced my username with that for the purposes of posting here.

**Comment by programarivm** [comment]
The MessagePack PECL extension needs to be installed.

```
pecl install msgpack
```

See:

- https://github.com/chesslablab/php-chess/issues/365

Keep it up,

**Comment by SmashedFrenzy16** [comment]
@programarivm, I also got another error that is the following (sorry for any inconveniences, it's the first time I'm using this PHP script for this task):

```
PHP Fatal error:  Uncaught Error: Call to undefined function Chess\Play\msgpack_unpack() in /home/smashedfrenzy16/Programming/PHP/vendor/chesslablab/php-chess/src/Play/RavPlay.php:43
Stack trace:
#0 /home/smashedfrenzy16/Programming/PHP/games-format.php(51): Chess\Play\RavPlay->__construct()
#1 {main}
  thrown in /home/smashedfrenzy16/Programming/PHP/vendor/chesslablab/php-chess/src/Play/RavPlay.php on line 43
```
I have `msgpack` installed as well.

PS: I switched to Ubuntu (as it's much easier to do on Linux) and installed everything that you told me to above, but I got this error.

**Comment by programarivm** [comment]
It seems as though the PECL extension is not installed or loaded.

Check out your `php.ini`.

```
php --ini
```

Make sure the extension is being loaded in the configuration file.

```
cat /etc/php/8.1/cli/php.ini | grep msgpack
extension=msgpack
```

Keep it up, and happy coding!

**Comment by SmashedFrenzy16** [comment]
@programarivm, thanks for all the help! The program now works!

**Comment by mobeendev** [comment]
@SmashedFrenzy16 from where did you installed the extension, I tried to set it up, but its now working.
Can you share some guidelines here for me and for others as well.
Thanks.

**Comment by SmashedFrenzy16** [comment]
@mobeendev, after following all of what @programarivm told me, I also had to install the following extension:

```
composer require chesslablab/php-chess
```

Basically to recap, you need to install `php-cli`, `php-dev`, PHP with an Apache2 module (if you want - I did because of one of the installing tutorials I was looking at) and composer to your machine. The in your project folder, run `composter install` after adding a `composer.json` file in there with the following contents:
```
{
    "require": {
        "php": ">=5.3.2",
        "chesslablab/php-chess": "^1.3"
    }
}
``` 
After that, get rid of the "/.." at the start of the line `require __DIR__  . '/../vendor/autoload.php';` in the PHP script. Then also remember to run the following command: `composer require chesslablab/php-chess`.

Now install PECL:

```
sudo apt install php-pear
```
Then I ran the following command to install `msgpack`:

```
sudo pecl install msgpack
```

After this, you need to add `msgpack` to your `php.ini` file. To do this, run:

```
sudo gedit /etc/php/8.1/cli/php.ini
```
Then in that file that opens, in the extensions list, add the msgpack extension, but unlike the other extensions, without the semi colon at the start of the line.

Then you can run your PHP file and it'll hopefully work!

PS: I used Ubuntu 22.04 Jammy Jellyfish for this. I would strongly recommend using macOS or Linux, and not Windows (as I found it a bit harder to use and it was not as popular in the PHP tutorial pages I looked through). Your installation paths/commands may vary.

**Comment by programarivm** [comment]
@mobeendev the installation process may vary depending on the operating system being used. Alternatively, Docker can be used out-of-the-box across multiple operating systems. This is how to run the staging environment.

```
docker compose -f docker-compose.staging.yml up -d
```

Happy learning!

**Comment by ArslanYM** [comment]
Can someone provide of a context for these issues?
